name: test

on:
  push:
    paths-ignore:
      - '**.md'
  pull_request:
  workflow_dispatch:

jobs:
  initial:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./
        id: action
        with:
          target: mecab mecab-ipadic-utf8 libmecab-dev
          command: apt-get install
          archive: /tmp/apt-archive.tz
          directory: /usr /var
          sudo: true
      - run: |
          tar tvfz /tmp/apt-archive.tz
