name: test

on:
  push:
    paths-ignore:
      - '**.md'
  pull_request:
  workflow_dispatch:

jobs:
  initial:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./
        id: action
        with:
          target: mecab mecab-ipadic-utf8 libmecab-dev
          command: apt-get install -qq
          archive: /tmp/apt-archive.tz
          sudo: true
          directory: >-
            /etc
            /usr/bin
            /usr/sbin
            /usr/lib
            /usr/share
            /var/lib
      - run: |
          tar tvfz /tmp/apt-archive.tz \
              usr/bin/mecab \
              usr/lib/mecab/mecab-dict-index \
              etc/alternatives/mecab-dictionary \
              var/lib/mecab/dic/ipadic-utf8/sys.dic
